# Generated by Django 2.1.4 on 2018-12-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contacts_date',
            new_name='contact_date',
        ),
    ]
